src/ScheduleMasterCore/Hos.ScheduleMaster.Web/Controllers/ConsoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hos.ScheduleMaster.Core;
using Hos.ScheduleMaster.Core.Interface;
using Hos.ScheduleMaster.Web.Extension;
using Microsoft.AspNetCore.Mvc;
using Hos.ScheduleMaster.Core.Models;
using Hos.ScheduleMaster.Core.Common;
using Hos.ScheduleMaster.Core.Dto;

namespace Hos.ScheduleMaster.Web.Controllers
{
    public class ConsoleController : AdminController
    {
        [Autowired]
        public IScheduleService _scheduleService { get; set; }

        [Autowired]
        public INodeService _nodeService { get; set; }

        public IActionResult Index()
        {
            ViewBag.CurrentAdmin = CurrentAdmin;
            return View();
        }

        public IActionResult MySchedule()
        {
            ViewBag.PagerQueryUrl = Url.Action("QueryCurrentUserPager", "Schedule");
            return View("../Schedule/Index");
        }

        public ActionResult Home()
        {
            //我负责的top任务，创建时间倒序
            var pager = new ListPager<ScheduleInfo>(1, 7);
            ViewBag.MySchedule = _scheduleService.QueryPager(pager, CurrentAdmin.Id).Rows;
            return View();
        }

        [HttpGet]
        public ActionResult GetHomeSummary()
        {
            //总任务数
            int task_total = _scheduleService.QueryScheduleCount(null);
            //运行中任务数
            int task_running = _scheduleService.QueryScheduleCount((int)ScheduleStatus.Running);
            //总用户数
            int user_total = _accountService.QueryUserCount(null);
            //总运行次数
            int trace_total = _scheduleService.QueryTraceCount(null);
            //累计运行成功次数
            int trace_success = _scheduleService.QueryTraceCount(1);
            //累计运行失败次数
            int trace_failed = _scheduleService.QueryTraceCount(2);
            //总节点数
            int worker_total = _nodeService.QueryWorkerCount(null);
            //工作中节点数
            int worker_running = _nodeService.QueryWorkerCount(2);
            //休息中节点数
            int worker_ready = _nodeService.QueryWorkerCount(1);
            //近一周运行成功数据
            object weekly_success = _scheduleService.QueryTraceWeeklyReport(1);
            //近一周运行失败数据
            object weekly_failed = _scheduleService.QueryTraceWeeklyReport(2);
            return this.JsonNet(true, data: new { task_total, task_running, user_total, trace_total, trace_success, trace_failed, worker_total, worker_running, worker_ready, weekly_success, weekly_failed });
        }
    }
}

src/ScheduleMasterCore/Hos.ScheduleMaster.Web/Controllers/StaticController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Hos.ScheduleMaster.Core;
using Hos.ScheduleMaster.Core.Common;
using Microsoft.AspNetCore.Mvc;

namespace Hos.ScheduleMaster.Web.Controllers
{
    /// <summary>
    /// 一些公共的静态页面
    /// </summary>
    public class StaticController : Controller
    {
        /// <summary>
        /// 404页面
        /// </summary>
        /// <returns></returns>
        public ActionResult Page404()
        {
            return View();
        }

        /// <summary>
        /// 下载插件包
        /// </summary>
        /// <param name="pluginName"></param>
        /// <returns></returns>
        public IActionResult DownloadPluginFile(string pluginName)
        {
            var path = $"{ConfigurationCache.PluginPathPrefix}\\{pluginName}.zip".ToPhysicalPath();
            //using (var stream = System.IO.File.OpenRead(path))
            {
                var stream = System.IO.File.OpenRead(path);
                return File(stream, "application/octet-stream", $"{pluginName}.zip");
            }
        }
    }
}

src/ScheduleMasterCore/Hos.ScheduleMaster.Web/Views/Static/Page404.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<!--
Beyond Admin - Responsive Admin Dashboard Template build with Twitter Bootstrap 3
Version: 1.0.0
Purchase: http://wrapbootstrap.com
-->

<html xmlns="http://www.w3.org/1999/xhtml">
<!--Head-->
<head>
    <meta charset="utf-8" />
    <title>Error 404 - Page Not Found</title>

    <meta name="description" content="Error 404 - Page Not Found" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" href="/assets/img/icon.png" type="image/x-icon">

    <!--Basic Styles-->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link id="bootstrap-rtl-link" href="" rel="stylesheet" />
    <link href="/assets/css/font-awesome.min.css" rel="stylesheet" />

    <!--Beyond styles-->
    <link id="beyond-link" href="/assets/css/beyond.min.css" rel="stylesheet" type="text/css" />

</head>
<!--Head Ends-->
<!--Body-->
<body class="body-404">
    <div class="error-header"> </div>
    <div class="container ">
        <section class="error-container text-center">
            <h1>404</h1>
            <div class="error-divider">
                <h2>page not found</h2>
                <p class="description">We Couldn’t Find This Page</p>
            </div>
            <a href="@Url.Action("Home","Console")" class="return-btn"><i class="fa fa-home"></i>Home</a>
        </section>
    </div>
</body>
<!--Body Ends-->
</html>