src/ScheduleMasterCore/Hos.ScheduleMaster.Web/Controllers/SystemController.cs
using Hos.ScheduleMaster.Core;
using Hos.ScheduleMaster.Core.Common;
using Hos.ScheduleMaster.Core.Interface;
using Hos.ScheduleMaster.Core.Models;
using Hos.ScheduleMaster.Web.Extension;
using Hos.ScheduleMaster.Web.Filters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hos.ScheduleMaster.Web.Controllers
{
    public class SystemController : AdminController
    {
        [Autowired]
        public ISystemService _systemService { get; set; }

        [Autowired]
        public INodeService _nodeService { get; set; }

        [Autowired]
        public IScheduleService _scheduleService { get; set; }

        // GET: System
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 节点列表页面
        /// </summary>
        /// <returns></returns>
        public ActionResult Node()
        {
            return View();
        }

        /// <summary>
        /// 节点分页数据
        /// </summary>
        /// <returns></returns>
        public ActionResult QueryNodePager(string keyword)
        {
            var pager = new ListPager<ServerNodeEntity>(PageIndex, PageSize);
            if (!string.IsNullOrEmpty(keyword))
            {
                pager.AddFilter(x => x.MachineName.Contains(keyword) || x.NodeName.Contains(keyword) || x.Host.Contains(keyword));
            }
            pager = _nodeService.QueryNodePager(pager);
            return GridData(pager.Total, pager.Rows);
        }

        /// <summary>
        /// 节点编辑页面
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public ActionResult NodeEdit(string name = "")
        {
            if (string.IsNullOrEmpty(name))
            {
                return View();
            }
            var entity = _nodeService.GetNodeByName(name);
            if (entity == null)
            {
                return PageNotFound();
            }
            return View(entity);
        }

        /// <summary>
        /// 保存节点信息
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        [HttpPost, AjaxRequestOnly]
        public ActionResult NodeSave(ServerNodeEntity entity)
        {
            if (ModelState.IsValid)
            {
                string savetype = Request.Form["savetype"].ToString();
                if (savetype == "edit")
                {
                    var result = _nodeService.EditNode(entity);
                    if (result)
                    {
                        return SuccessTip("编辑节点成功！", Url.Action("Node"));
                    }
                    return DangerTip("编辑节点失败！");
                }
                else if (savetype == "add")
                {
                    if (_nodeService.GetNodeByName(entity.NodeName) != null)
                    {
                        return DangerTip("节点名称已存在！");
                    }
                    var result = _nodeService.AddNode(entity);
                    if (result)
                    {
                        return SuccessTip("新增节点成功！", Url.Action("Node"));
                    }
                    return DangerTip("新增节点失败！");
                }
            }
            return DangerTip("数据验证失败！");
        }

        /// <summary>
        /// 节点连接
        /// </summary>
        /// <returns></returns>
        [HttpPost, AjaxRequestOnly]
        public async Task<ActionResult> NodeConnect(string name)
        {
            var result = await _nodeService.NodeSwich(name, 1);
            if (result)
            {
                return this.JsonNet(true, "操作成功！");
            }
            return this.JsonNet(false, "操作失败！");
        }

        /// <summary>
        /// 节点启用
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, AjaxRequestOnly]
        public async Task<ActionResult> NodeEnable(string name)
        {
            var result = await _nodeService.NodeSwich(name, 3);
            if (result)
            {
                return this.JsonNet(true, "操作成功！");
            }
            return this.JsonNet(false, "操作失败！");
        }

        /// <summary>
        /// 节点停机
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, AjaxRequestOnly]
        public async Task<ActionResult> NodeDisable(string name)
        {
            var result = await _nodeService.NodeSwich(name, 2);
            if (result)
            {
                return this.JsonNet(true, "操作成功！");
            }
            return this.JsonNet(false, "操作失败！");
        }

        /// <summary>
        /// 节点删除
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        [HttpPost, AjaxRequestOnly]
        public ActionResult NodeDelete(string name)
        {
            var result = _nodeService.DeleteNode(name);
            if (result)
            {
                return this.JsonNet(true, "删除成功！");
            }
            return this.JsonNet(false, "删除失败！");
        }

        /// <summary>
        /// 参数配置页面
        /// </summary>
        /// <returns></returns>
        public ActionResult Config()
        {
            var data = _systemService.GetConfigList();
            return View(data);
        }

        /// <summary>
        /// 保存参数配置
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SaveConfig(IFormCollection form)
        {
            Dictionary<string, string> items = new Dictionary<string, string>();
            foreach (string key in form.Keys)
            {
                items.Add(key, form[key]);
            }
            bool result = _systemService.SaveConfig(items, CurrentAdmin.UserName);
            if (result)
            {
                ConfigurationCache.Reload();
                return SuccessTip("保存成功！");
            }
            return DangerTip("保存失败！");
        }

        /// <summary>
        /// 日志列表页面
        /// </summary>
        /// <returns></returns>
        public ActionResult Log()
        {
            return View();
        }

        /// <summary>
        /// 查询日志记录
        /// </summary>
        /// <param name="enddate"></param>
        /// <param name="sid"></param>
        /// <param name="startdate"></param>
        /// <param name="category"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult QueryLogPager(DateTime? startdate, DateTime? enddate, Guid? sid, int? category)
        {
            var pager = new ListPager<SystemLogEntity>(PageIndex, PageSize);
            if (sid.HasValue)
            {
                pager.AddFilter(m => m.ScheduleId == sid);
            }
            if (category.HasValue && category.Value > 0)
            {
                pager.AddFilter(m => m.Category == category);
            }
            if (startdate.HasValue)
            {
                pager.AddFilter(m => m.CreateTime >= startdate);
            }
            if (enddate.HasValue)
            {
                pager.AddFilter(m => m.CreateTime <= enddate);
            }
            pager = _systemService.QueryLogPager(pager);
            return GridData(pager.Total, pager.Rows);
        }

        /// <summary>
        /// 清理日志页面
        /// </summary>
        /// <returns></returns>
        public ActionResult ClearLog()
        {
            List<SelectListItem> selectData = new List<SelectListItem>();
            selectData.Add(new SelectListItem() { Text = "系统日志", Value = "0" });
            selectData.AddRange(_scheduleService.QueryAll().Select(row => new SelectListItem
            {
                Text = row.Title,
                Value = row.Id.ToString(),
                Selected = false
            }));
            ViewBag.TaskList = selectData;
            return View();
        }


        /// <summary>
        /// 清理日志
        /// </summary>
        /// <param name="sid"></param>
        /// <param name="category"></param>
        /// <param name="startdate"></param>
        /// <param name="enddate"></param>
        /// <returns></returns>
        [HttpPost, AjaxRequestOnly]
        public async Task<ActionResult> ClearLog(Guid? sid, int? category, DateTime? startdate, DateTime? enddate)
        {
            var result = await _systemService.DeleteLog(sid, category, startdate, enddate);
            if (result > 0)
            {
                return this.JsonNet(true, $"清理成功！本次清理【{result}】条");
            }
            return this.JsonNet(false, "没有符合条件的记录！");
        }
    }
}

src/ScheduleMasterCore/Hos.ScheduleMaster.Web/Views/System/ClearLog.cshtml
<div class="page-body">
    <div class="widget">
        <div class="widget-header bordered-bottom bordered-lightred">
            <span class="widget-caption">清理日志</span>
        </div>
        <div class="widget-body">
            <form class="form-horizontal" method="post" id="form1" novalidate="novalidate">
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label no-padding-right">日志类型</label>
                    <div class="col-sm-6">
                        <select class="form-control" id="Category">
                            <option value="0">全部类型</option>
                            <option value="1">信息</option>
                            <option value="2">警告</option>
                            <option value="3">异常</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label no-padding-right">任务名称</label>
                    <div class="col-sm-6">
                        @Html.DropDownList("sid", ViewBag.TaskList as List<SelectListItem>, "全部任务", new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label no-padding-right">时间区间</label>
                    <div class="col-sm-6">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default quickselect" data-date="@DateTime.Today.AddDays(-7).ToString("yyyy-MM-dd")">
                                一周前
                            </button>
                            <button type="button" class="btn btn-default quickselect" data-date="@DateTime.Today.AddMonths(-1).ToString("yyyy-MM-dd")">
                                一月前
                            </button>
                            <button type="button" class="btn btn-default quickselect" data-date="@DateTime.Today.AddMonths(-3).ToString("yyyy-MM-dd")">
                                三月前
                            </button>
                            <button type="button" class="btn btn-default quickselect" data-date="@DateTime.Today.AddMonths(-6).ToString("yyyy-MM-dd")">
                                半年前
                            </button>
                            <button type="button" class="btn btn-default quickselect" data-date="@DateTime.Today.AddYears(-1).ToString("yyyy-MM-dd")">
                                一年前
                            </button>
                            <button type="button" class="btn btn-default quickselect" data-date="@DateTime.Today.AddYears(-2).ToString("yyyy-MM-dd")">
                                两年前
                            </button>
                        </div>
                        <div class="checkbox" style="display: inline-block;">
                            <label>
                                <input type="checkbox" id="ckb_daterange">
                                <span class="text">自定义</span>
                            </label>
                        </div>
                        <div class="help-block hide" id="div_daterange">
                            <div class="col-sm-5">
                                <div class="form-group">
                                    <span class="input-icon icon-right">
                                        <input type="text" class="form-control date-picker" name="StartDate" id="StartDate" placeholder="开始日期">
                                        <i class="fa fa-calendar"></i>
                                    </span>
                                </div>
                            </div>
                            <div class="col-sm-5">
                                <div class="form-group">
                                    <span class="input-icon icon-right">
                                        <input type="text" class="form-control" name="EndDate" id="EndDate" placeholder="结束日期">
                                        <i class="fa fa-calendar"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button id="sbtn_form1" type="button" class="btn btn-primary">提  交</button>
                        <button type="button" class="btn btn-default" onclick="history.back();">返  回</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

@section scripts{
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/assets/js/laydate5.0.9/laydate.js"></script>
    <script type="text/javascript">
        hos.ui.util.breadCrumb("系统日志-清理");
        $(function () {
            var startTime = laydate.render({
                elem: '#StartDate', type: 'date', done: function (value, date, endDate) {
                    date.month = date.month - 1;
                    endTime.config.min = date;
                    $(endTime.config.elem).focus();
                    $(".quickselect").removeClass("btn-primary");
                }
            });
            var endTime = laydate.render({
                elem: '#EndDate', type: 'date', done: function (value, date, endDate) {
                    date.month = date.month - 1;
                    startTime.config.max = date;
                    $(".quickselect").removeClass("btn-primary");
                }
            });
            $("#ckb_daterange").click(function () {
                if (this.checked) {
                    $("#div_daterange").removeClass("hide");
                    $(".quickselect").removeClass("btn-primary");
                } else {
                    $("#div_daterange").addClass("hide");
                }
            });
            $(".quickselect").bind("click", function () {
                if (!$(this).hasClass("btn-primary")) {
                    $(this).addClass("btn-primary").siblings().removeClass("btn-primary");
                    $("#StartDate").val('');
                    $("#EndDate").val($(this).attr("data-date"));
                }
            })
            hos.ui.util.formSubmit("form1", function (data) {
                if (!data.StartDate && !data.EndDate) {
                    hos.ui.util.errorTip("必须选择时间范围！");
                    return;
                }
                if (confirm('确认要按所选条件清理日志吗？此操作不可恢复~')) {
                    hos.ui.util.postJson("@Url.Action("ClearLog")", data);
                }
            });
        })
    </script>
}

src/ScheduleMasterCore/Hos.ScheduleMaster.Web/Views/System/Config.cshtml
@using Hos.ScheduleMaster.Core.Models
@model List<SystemConfigEntity>

@{
    var groupList = Model.Select(x => x.Group).Distinct().ToArray();
}

<div class="page-body">
    <div class="widget">

        <div class="widget-body">
            <form class="form-horizontal" action="@Url.Action("SaveConfig","System")" data-ajax="true" data-ajax-method="post" id="form1" data-ajax-complete="" data-ajax-begin="" novalidate="novalidate">
                <div class="form-group">
                    <div class="col-sm-1">
                        <button type="submit" class="btn btn-primary" onclick="return true;">保  存</button>
                    </div>
                </div>
                <div class="tabbable">
                    <ul class="nav nav-tabs" id="myTab">
                        @for (int i = 0; i < groupList.Length; i++)
                        {
                            <li class="@(i==0?"active":"")">
                                <a data-toggle="tab" href="#group_@i">@groupList[i]</a>
                            </li>
                        }
                    </ul>
                    <div class="tab-content">
                        @for (int i = 0; i < groupList.Length; i++)
                        {
                            <div id="group_@i" class="tab-pane @(i==0?"active":"")">
                                @{
                                    var items = Model.Where(x => x.Group == groupList[i]).OrderBy(x => x.Sort).ToList();
                                    foreach (var item in items)
                                    {
                                        <div class="form-group">
                                            <label for="" class="col-sm-2 control-label no-padding-right">@item.Name</label>
                                            <div class="col-sm-6">
                                                <input type="text" class="form-control" name="@item.Key" placeholder="" value="@item.Value" @(item.IsReuired ? "required=''" : "")>
                                                <p class="help-block">@item.Remark</p>
                                            </div>
                                        </div>
                                    }
                                }
                            </div>
                        }
                    </div>
                </div>
                <br />
                <br />
            </form>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/js/jquery.unobtrusive-ajax.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script type="text/javascript">
        hos.ui.util.breadCrumb("系统设置-参数配置");
        $(function () {
            hos.ui.util.formValidate("form1");
        })
    </script>
}

src/ScheduleMasterCore/Hos.ScheduleMaster.Web/Views/System/Log.cshtml
@{
    ViewBag.Title = "Log";
}
<style type="text/css">
    .pull-left.pagination-detail {
        display: none;
    }
</style>
<link href="~/assets/js/bootstrap-table/bootstrap-table.min.css" rel="stylesheet" />


<div class="page-body">
    <div id="serch-form" class="form-inline">
        <a href="@Url.Action("ClearLog")" class="btn btn-danger">清理日志</a>
        <div class="pull-right">
            <div class="form-group">
                <span class="input-icon icon-right">
                    <input type="text" class="form-control date-picker" value="@DateTime.Now.AddDays(-7).ToString("yyyy-MM-dd")" name="StartDate" id="StartDate" placeholder="开始时间">
                    <i class="fa fa-calendar"></i>
                </span>
            </div>
            -
            <div class="form-group">
                <span class="input-icon icon-right">
                    <input type="text" class="form-control" value="@DateTime.Now.AddDays(1).ToString("yyyy-MM-dd")" name="EndDate" id="EndDate" placeholder="结束时间">
                    <i class="fa fa-calendar"></i>
                </span>
            </div>
            <div class="form-group">
                <select class="form-control" id="Category">
                    <option value="0">全部类型</option>
                    <option value="1">信息</option>
                    <option value="2">警告</option>
                    <option value="3">异常</option>
                </select>
            </div>
            <div class="input-group">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" id="btn_table_search" onclick="grid.reload();"><i class="fa fa-search blue"></i></button>
                </span>
            </div>
        </div>
    </div>
    <table id="table" class="mychar1-table"></table>
</div>


@section scripts{
    <script src="~/assets/js/bootstrap-table/bootstrap-table.min.js"></script>
    <script src="~/assets/js/bootstrap-table/bootstrap-table-zh-CN.min.js"></script>
    <script src="~/assets/js/laydate5.0.9/laydate.js"></script>
    <script src="~/assets/js/bootbox/bootbox.js"></script>

    <script>
        hos.ui.util.breadCrumb("系统日志");
        var startTime = laydate.render({
            elem: '#StartDate', type: 'date', done: function (value, date, endDate) {
                date.month = date.month - 1;
                endTime.config.min = date;
                $(endTime.config.elem).focus();
            }
        });
        var endTime = laydate.render({
            elem: '#EndDate', type: 'date', done: function (value, date, endDate) {
                date.month = date.month - 1;
                startTime.config.max = date;
            }
        });
        var grid = hos.ui.ctrl.gridView("table", {
            url: '/System/QueryLogPager',
            columns: [
                { field: 'Node', title: '节点', align: 'center', width: '8', widthUnit: '%' },
                { field: 'Category', title: '类型', align: 'center', width: '8', widthUnit: '%', formatter: function (value, row, index) {
                    var text = '';
                    switch (value) {
                        case 1:
                            text = '<label style="color:#38b03f">信息</label>';
                            break;
                        case 2:
                            text = '<label style="color:#f1a325">警告</label>';
                            break;
                        case 3:
                            text = '<label style="color:red">异常</label>';
                            break;
                    }
                    return text;
                }
                },
                { field: 'CreateTime', title: '生成时间', align: 'center', width: '12', widthUnit: '%' },
                {
                    field: 'Message', title: '内容', width: '80', widthUnit: '%', formatter: function (value, row, index) {
                        var text = value;
                        if (row.Category == 3) {
                            text += '     <a class="label label-danger graded" onclick="showStackTrace(' + index + ')">查看堆栈</a>';
                        }
                        return text;
                    }
                }
            ]
        });
        $('#btn_clear').on("click", function () {
            var params = {
                task: $("#Task").val(),
                category: $("#Category").val(),
            };
            hos.ui.util.postJson("@Url.Action("ClearLog")", params)
        })

        function showStackTrace(index) {
            bootbox.dialog({
                message: "<xmp style='overflow: auto;'>"+grid.getData(index).StackTrace+"</xmp>",
                title: "堆栈信息",
                size: "lg"
            });
        }
    </script>
}

src/ScheduleMasterCore/Hos.ScheduleMaster.Web/Views/System/Node.cshtml
@{
    ViewData["Title"] = "Node";
}

<link href="~/assets/js/bootstrap-table/bootstrap-table.min.css" rel="stylesheet" />


<div class="page-body">
    <div id="serch-form" class="form-inline">
        <a href="@Url.Action("NodeEdit","System")" class="btn btn-primary">添加节点</a>
        <div class="pull-right">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="节点名\主机名\主机地址" id="keyword">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" id="btn_table_search" onclick="grid.reload();"><i class="fa fa-search blue"></i></button>
                </span>
            </div>
        </div>
    </div>
    <table id="table" class="mychar1-table"></table>
</div>


@section scripts{
    <!--Page Related Scripts-->
    <script src="~/assets/js/bootstrap-table/bootstrap-table.min.js"></script>
    <script src="~/assets/js/bootstrap-table/bootstrap-table-zh-CN.min.js"></script>
    <script>
        hos.ui.util.breadCrumb("节点管理");
        var grid = hos.ui.ctrl.gridView("table", {
            url: '/System/QueryNodePager',
            columns: [
                { field: 'NodeName', title: '节点名称', align: 'center', width: '10' },
                {
                    field: 'NodeType', title: '节点类型', align: 'center', width: '8', formatter: function (value, row, index) {
                        if (value == "master") {
                            return '<span class="badge badge-primary">' + value+'</span >';
                        }
                        return value;
                    }
                },
                { field: 'MachineName', title: '主机名', align: 'center', width: '8' },
                { field: 'AccessProtocol', title: '访问协议', align: 'center', width: '8' },
                { field: 'Host', title: '主机地址', width: '15' },
                { field: 'LastUpdateTime', title: '最后更新时间', align: 'center', width: '15' },
                {
                    field: 'Status', title: '状态', align: 'center', width: '10', formatter: function (value, row, index) {
                        var dict = [
                            "<span class='label label-danger graded'>下线</span>",
                            "<span class='label label-azure graded'>空闲</span>",
                            "<span class='label label-green graded'>运行</span>"
                        ];
                        return dict[value];
                    }
                },
                { field: 'Priority', title: '权重', align: 'center', width: '5' },
                { field: 'MaxConcurrency', title: '任务并发量', align: 'center', width: '10' },
                {
                    title: '操作', field: 'id', align: 'center', formatter: function (value, row, index) {
                        var s = '<a href="/System/NodeEdit?name=' + row.NodeName + '" class="btn btn-xs">编辑</a>  ';
                        if (row.NodeType == "master") return s;
                        if (row.Status == 0) {
                            return s + '<button class="btn btn-xs" onclick="handlers.nodeConnect(\'' + row.NodeName + '\')">连接</button>  <button class="btn btn-xs btn-danger" onclick="handlers.nodeDelete(\'' + row.NodeName + '\')">删除</button>  ';
                        }
                        if (row.Status == 1) {
                            return s + '<button class="btn btn-xs btn-primary" onclick="handlers.nodeEnable(\'' + row.NodeName + '\')">启用</button>  ';
                        }
                        if (row.Status == 2) {
                            return s + '<button class="btn btn-xs btn-azure" onclick="handlers.nodeDisable(\'' + row.NodeName + '\')">休息</button>  ';
                        }
                    }
                }
            ]
        });
        var handlers = {
            nodeConnect: function (value) {
                this.request(value, '/System/NodeConnect?name=' + value, "连接");
            },
            nodeEnable: function (value) {
                this.request(value, '/System/NodeEnable?name=' + value, "启用");
            },
            nodeDisable: function (value) {
                this.request(value, '/System/NodeDisable?name=' + value, "休息");
            },
            nodeDelete: function (value) {
                this.request(value, '/System/NodeDelete?name=' + value, "删除");
            },
            request: function (title, url, action) {
                hos.ui.util.confirm('确定要 <span style="color:red" > ' + action + '</span>【' + title + '】吗？',
                    function () {
                        hos.ui.util.postJson(url, null, function () { grid.reload(); })
                    });
            }
        }
    </script>
}